const ADJECTIVES: [&str; 64] = [
    "soggy",
    "grumpy",
    "wobbly",
    "sneaky",
    "confused",
    "fluffy",
    "jolly",
    "sleepy",
    "bouncy",
    "cranky",
    "dizzy",
    "giddy",
    "goofy",
    "grouchy",
    "hasty",
    "itchy",
    "jittery",
    "lumpy",
    "mellow",
    "nervous",
    "noisy",
    "peppy",
    "plucky",
    "quirky",
    "rowdy",
    "scruffy",
    "shaky",
    "silly",
    "snappy",
    "sparkly",
    "squeaky",
    "stubborn",
    "sulky",
    "sunny",
    "tangy",
    "twitchy",
    "wacky",
    "whimsical",
    "zany",
    "bashful",
    "breezy",
    "chatty",
    "clumsy",
    "cuddly",
    "dapper",
    "feisty",
    "fidgety",
    "frisky",
    "gloomy",
    "hungry",
    "jumpy",
    "kooky",
    "lazy",
    "merry",
    "nifty",
    "perky",
    "pudgy",
    "rumpled",
    "spunky",
    "wiggly",
    "zesty",
    "brisk",
    "crispy",
    "dusty",
];
const NOUNS: [&str; 64] = [
    "walrus",
    "waffle",
    "pickle",
    "noodle",
    "toaster",
    "otter",
    "heron",
    "badger",
    "biscuit",
    "bagel",
    "muffin",
    "pretzel",
    "turnip",
    "pancake",
    "kazoo",
    "banjo",
    "llama",
    "penguin",
    "platypus",
    "narwhal",
    "hedgehog",
    "gecko",
    "moose",
    "ferret",
    "marmot",
    "pelican",
    "puffin",
    "quokka",
    "wombat",
    "tapir",
    "lemur",
    "newt",
    "goose",
    "cactus",
    "pumpkin",
    "potato",
    "radish",
    "cabbage",
    "sprout",
    "crouton",
    "dumpling",
    "nugget",
    "pudding",
    "spatula",
    "teapot",
    "kettle",
    "mitten",
    "sock",
    "slipper",
    "button",
    "pebble",
    "trombone",
    "ukulele",
    "bubble",
    "balloon",
    "doughnut",
    "gadget",
    "sandwich",
    "croissant",
    "tortoise",
    "beetle",
    "meatball",
    "acorn",
    "raccoon",
];

/// First free `ADJECTIVE-NOUN` at or after `seed % 4096`, wrapping; `None` when all are taken.
/// The seed is supplied so callers can use randomness while tests can use literal indices.
pub fn pick(taken: &[String], seed: u64) -> Option<String> {
    const COMBINATIONS: usize = ADJECTIVES.len() * NOUNS.len();
    let start = (seed % COMBINATIONS as u64) as usize;
    for offset in 0..COMBINATIONS {
        let index = (start + offset) % COMBINATIONS;
        let candidate = format!(
            "{}-{}",
            ADJECTIVES[index / NOUNS.len()],
            NOUNS[index % NOUNS.len()]
        );
        if !taken.iter().any(|name| name == &candidate) {
            return Some(candidate);
        }
    }
    None
}
